"use client";

import { useEffect, useMemo, useState } from "react";
import dynamic from "next/dynamic";
import { AlertCircle, Database, Loader2, MapPin } from "lucide-react";
import type { RajukDistrict, RajukMauza, RajukPlotFeature, RajukUpazila } from "@/src/types/rajuk-runtime";
import { areaFromPlotAttributes, formatAreaValue } from "@/src/modules/land/plotArea";

const PlotMap = dynamic(() => import("@/src/shared/components/PlotMap"), { ssr: false });
type PlotTab = "rs" | "ms";
async function apiJson(url: string) { const r = await fetch(url, { cache: "no-store" }); const d = await r.json(); if (!r.ok) throw new Error(d.error || `Request failed (${r.status})`); return d; }
function plotNo(f: RajukPlotFeature, tab: PlotTab) { const a = f.attributes as Record<string, unknown>; return String(tab === "ms" ? a.ms_plot_no ?? a.plot_no ?? "" : a.rs_plot_no ?? a.plot_no ?? "").trim(); }

function useAddressCascade(kind: PlotTab) {
  const [districts, setDistricts] = useState<RajukDistrict[]>([]), [upazilas, setUpazilas] = useState<RajukUpazila[]>([]), [mouzas, setMouzas] = useState<RajukMauza[]>([]);
  const [dGuid, setDGuid] = useState(""), [tGuid, setTGuid] = useState(""), [mauzaId, setMauzaId] = useState(""), [loading, setLoading] = useState(""), [error, setError] = useState("");
  useEffect(() => { setLoading("district"); setError(""); apiJson(`/api/rajuk/query?action=districts`).then(d => setDistricts(d.features ?? [])).catch(e => setError(e instanceof Error ? e.message : "District load failed")).finally(() => setLoading("")); }, [kind]);
  useEffect(() => { setUpazilas([]); setMouzas([]); setTGuid(""); setMauzaId(""); if (!dGuid) return; setLoading("upazila"); setError(""); apiJson(`/api/rajuk/query?action=upazilas&d_guid=${encodeURIComponent(dGuid)}`).then(d => setUpazilas(d.features ?? [])).catch(e => setError(e instanceof Error ? e.message : "Upazila load failed")).finally(() => setLoading("")); }, [dGuid, kind]);
  useEffect(() => { setMouzas([]); setMauzaId(""); if (!tGuid) return; setLoading("mouza"); setError(""); apiJson(`/api/rajuk/query?action=mouzas&t_guid=${encodeURIComponent(tGuid)}&kind=${kind}`).then(d => setMouzas(d.features ?? [])).catch(e => setError(e instanceof Error ? e.message : `${kind.toUpperCase()} Mouza load failed`)).finally(() => setLoading("")); }, [tGuid, kind]);
  return { districts, upazilas, mouzas, dGuid, setDGuid, tGuid, setTGuid, mauzaId, setMauzaId, loading, error, setError, selectedUpazila: upazilas.find(x => x.t_guid === tGuid), selectedMouza: mouzas.find(x => x.m_guid === mauzaId) };
}

function SelectField({ label, loading, children, ...props }: any) {
  return <div className="relative"><label className="block text-sm font-medium">{label}</label><div className="relative mt-1"><select {...props} className={`w-full appearance-none rounded-xl border bg-white px-3 py-2.5 pr-10 ${props.className ?? ""}`}>{children}</select>{loading && <Loader2 size={17} className="pointer-events-none absolute right-3 top-1/2 -translate-y-1/2 animate-spin text-[#006a4e]" />}</div></div>;
}
function AddressFields({ loc, tab }: { loc: ReturnType<typeof useAddressCascade>; tab: PlotTab }) {
  return <>
    <div className="sm:col-span-2"><SelectField label="Select District" value={loc.dGuid} onChange={(e: any) => loc.setDGuid(e.target.value)} disabled={loc.loading === "district"} loading={loc.loading === "district"}><option value="">District নির্বাচন করুন</option>{loc.districts.map(d => <option key={d.d_guid} value={d.d_guid}>{d.m_district}</option>)}</SelectField></div>
    <SelectField label="Select Upazila" value={loc.tGuid} onChange={(e: any) => loc.setTGuid(e.target.value)} disabled={!loc.dGuid || loc.loading === "upazila"} loading={loc.loading === "upazila"}><option value="">Upazila নির্বাচন করুন</option>{loc.upazilas.map(u => <option key={u.t_guid} value={u.t_guid}>{u.upazila_ps}</option>)}</SelectField>
    <SelectField label={`Select ${tab.toUpperCase()} Mouza + JL`} value={loc.mauzaId} onChange={(e: any) => loc.setMauzaId(e.target.value)} disabled={!loc.tGuid || loc.loading === "mouza"} loading={loc.loading === "mouza"}><option value="">{loc.loading === "mouza" ? "Loading…" : `${tab.toUpperCase()} Mouza নির্বাচন করুন`}</option>{loc.mouzas.map(m => <option key={m.m_guid} value={m.m_guid}>{m.mauza} — JL {m.jl_no}</option>)}</SelectField>
  </>;
}

function PlotSearch({ tab }: { tab: PlotTab }) {
  const loc = useAddressCascade(tab); const [plots, setPlots] = useState<RajukPlotFeature[]>([]); const [selected, setSelected] = useState<RajukPlotFeature | null>(null); const [plot, setPlot] = useState(""); const [loading, setPlotLoading] = useState(false);
  useEffect(() => { setPlots([]); setSelected(null); setPlot(""); if (!loc.selectedMouza || !loc.selectedUpazila) return; setPlotLoading(true); loc.setError(""); const q = new URLSearchParams({ action: "plots", kind: tab, mouza: loc.selectedMouza.mauza, jl: String(loc.selectedMouza.jl_no), upazila: loc.selectedUpazila.upazila_ps, limit: "2000" }); apiJson(`/api/rajuk/query?${q}`).then(d => setPlots((d.features ?? []) as RajukPlotFeature[])).catch(e => loc.setError(e instanceof Error ? e.message : `${tab.toUpperCase()} plot load failed`)).finally(() => setPlotLoading(false)); }, [tab, loc.selectedMouza, loc.selectedUpazila]);
  const options = useMemo(() => plots.map(f => ({ f, n: plotNo(f, tab) })).filter(x => x.n), [plots, tab]); const error = loc.error;
  return <>
    <section className="rounded-2xl border bg-white p-5 shadow-sm md:p-6"><h2 className="mb-1 font-bold">{tab.toUpperCase()} plot search</h2><p className="mb-4 text-xs text-slate-500">{tab === "rs" ? "RS address + FeatureServer/0" : "MS address + FeatureServer/5 — District → Upazila → Mouza/JL → Plot all from FeatureServer/5"}</p><div className="grid gap-3 sm:grid-cols-2"><AddressFields loc={loc} tab={tab}/><div className="relative sm:col-span-2"><label className="block text-sm font-medium">Select {tab.toUpperCase()} Plot</label><div className="relative mt-1"><select value={plot} onChange={e => { setPlot(e.target.value); setSelected(options.find(x => x.n === e.target.value)?.f ?? null); }} disabled={!loc.selectedMouza || loading} className="w-full appearance-none rounded-xl border bg-white px-3 py-2.5 pr-10"><option value="">{loading ? "Loading plots…" : `Select ${tab.toUpperCase()} plot`}</option>{options.map(x => <option key={String(x.f.attributes.objectid)} value={x.n}>{x.n}</option>)}</select>{loading && <Loader2 size={17} className="pointer-events-none absolute right-3 top-1/2 -translate-y-1/2 animate-spin text-[#006a4e]" />}</div></div></div></section>
    {error && <div className="flex gap-2 rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700"><AlertCircle size={18}/>{error}</div>}
    {options.length > 0 && <section className="rounded-2xl border bg-white p-5 shadow-sm"><div className="mb-3 flex items-center justify-between"><div><h2 className="font-bold">{tab.toUpperCase()} plot results</h2><p className="text-xs text-slate-500">{options.length} plot boundaries available on the map</p></div><MapPin size={20} className="text-[#006a4e]"/></div><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{options.map(x => <button key={String(x.f.attributes.objectid)} type="button" onClick={() => { setPlot(x.n); setSelected(x.f); }} className={`rounded-xl border p-3 text-left transition hover:border-[#006a4e] hover:bg-emerald-50 ${selected === x.f ? "border-[#006a4e] bg-emerald-50 ring-1 ring-[#006a4e]" : "bg-white"}`}><div className="font-semibold">{tab.toUpperCase()} Plot {x.n}</div><div className="mt-1 text-xs text-slate-500">Click to highlight boundary</div></button>)}</div></section>}
    {selected && <section className="space-y-4 rounded-2xl border bg-white p-5 shadow-sm"><div><h2 className="font-bold">{tab.toUpperCase()} Plot {plotNo(selected, tab)}</h2><p className="text-xs text-slate-500">Selected boundary highlighted; all results remain visible.</p></div><PlotMap feature={selected} features={plots}/><div className="overflow-x-auto rounded-xl border"><table className="w-full text-sm"><tbody>{[["Plot No", plotNo(selected, tab)], ["JL No", String(selected.attributes.jl_no ?? selected.attributes.rs_jl_no ?? selected.attributes.ms_jl_no ?? "—")], ["Mouza", String(selected.attributes.mauza ?? selected.attributes.rs_mauza_name ?? selected.attributes.ms_mauza_name ?? "—")], ["Upazila", String(selected.attributes.upazila_ps ?? selected.attributes.thana_upazila ?? "—")], ["District", String(selected.attributes.m_district ?? selected.attributes.district ?? "—")]].map(([k,v]) => <tr key={k}><th className="w-1/3 border-b bg-slate-50 px-4 py-2.5 text-left">{k}</th><td className="border-b px-4 py-2.5">{v}</td></tr>)}</tbody></table></div>{(() => { const a = areaFromPlotAttributes(selected.attributes as Record<string, unknown>); return a.isValid ? <div className="rounded-xl border border-emerald-200 p-4"><h3 className="mb-2 font-semibold">Calculated area</h3><div className="grid grid-cols-2 gap-2 text-sm">{[["sq ft",a.sqFt],["shotok",a.shotok],["katha",a.katha],["bigha",a.bigha],["acre",a.acre]].map(([k,v]) => <div key={String(k)}><span className="text-slate-500">{k}: </span><b>{formatAreaValue(v as number)}</b></div>)}</div></div> : null; })()}</section>}
  </>;
}
export default function RajukTestPage() { const [tab, setTab] = useState<PlotTab>("rs"); return <main className="min-h-screen bg-slate-50 px-4 py-8 text-slate-900 md:px-8"><div className="mx-auto max-w-5xl space-y-6"><header><div className="flex items-center gap-2 text-2xl font-bold"><Database className="text-[#006a4e]"/> RAJUK Runtime Test</div><p className="mt-1 text-sm text-slate-500">RS → FeatureServer/0 · MS → FeatureServer/5 · independent address cascades</p></header><div className="flex gap-1 rounded-xl border bg-slate-100 p-1"><button onClick={() => setTab("rs")} className={`flex-1 rounded-lg px-4 py-2.5 text-sm font-semibold ${tab === "rs" ? "bg-white text-[#006a4e] shadow-sm" : "text-slate-600"}`}>RS plot search</button><button onClick={() => setTab("ms")} className={`flex-1 rounded-lg px-4 py-2.5 text-sm font-semibold ${tab === "ms" ? "bg-white text-[#006a4e] shadow-sm" : "text-slate-600"}`}>MS plot search</button></div>{tab === "rs" ? <PlotSearch tab="rs"/> : <PlotSearch tab="ms"/>}</div></main>; }
