import "server-only";

import { jsPDF } from "jspdf";
import { getPlots } from "./rajukQuery.service";
import { RAJUK_DB } from "./rajukLayers.service";
import { getValidToken } from "./rajukAuth.service";
import type { RajukPlotFeature } from "@/src/types/rajuk-runtime";
import { drawAdaptivePlotLabels, drawNorthArrow, drawScaleBar, drawScaleText, type GeoExtent } from "./mouzaCartography";

export type MouzaPublicationRequest = { mouza: string; jl?: string; layers: "rs" | "ms" | "combined"; satellite?: boolean };
export type MouzaPublicationResult = { filename: string; contentType: "application/pdf"; body: Buffer; meta: { mouza: string; width: number; height: number; zoom: number; resolution: number; crs: string; extent: GeoExtent; tileCount: number; plotCount: number; satellite: boolean } };
type Ring = number[][]; type Polygon = { rings: Ring[] }; type MouzaRow = { attributes: Record<string, unknown>; geometry?: Polygon };
const PAGE_W=420,PAGE_H=297,MARGIN=14,MAP_TOP=26,MAP_BOTTOM=25,DRAW_W=PAGE_W-MARGIN*2,DRAW_H=PAGE_H-MAP_TOP-MAP_BOTTOM,PAGE_ASPECT=DRAW_W/DRAW_H,SAT_TIMEOUT=15_000,SAT_W=3508,SAT_H=2480,MAX_NEIGHBORS=24;
const text=(a:Record<string,unknown>,keys:string[])=>{for(const k of keys){const v=String(a[k]??"").trim();if(v)return v;}return ""};
const safePart=(v:string)=>v.replace(/[^\p{L}\p{N}]+/gu,"-").replace(/^-+|-+$/g,"")||"mouza";
function isMs(f:RajukPlotFeature){const a=f.attributes as Record<string,unknown>;return a._layer_source==="ms"||a.plot_kind==="ms"||Boolean(String(a.ms_plot_no??"").trim());}
function extentOf(features:RajukPlotFeature[]):GeoExtent|null{let xmin=Infinity,ymin=Infinity,xmax=-Infinity,ymax=-Infinity;for(const f of features)for(const r of f.geometry?.rings??[])for(const p of r){const x=Number(p[0]),y=Number(p[1]);if(Number.isFinite(x)&&Number.isFinite(y)){xmin=Math.min(xmin,x);ymin=Math.min(ymin,y);xmax=Math.max(xmax,x);ymax=Math.max(ymax,y);}}return Number.isFinite(xmin)?{xmin,ymin,xmax,ymax}:null;}
function expandExtent(e:GeoExtent,factor=1.08):GeoExtent{const cx=(e.xmin+e.xmax)/2,cy=(e.ymin+e.ymax)/2,w=Math.max(e.xmax-e.xmin,1e-12)*factor,h=Math.max(e.ymax-e.ymin,1e-12)*factor;let fw=w,fh=h;if(w/h<PAGE_ASPECT)fw=h*PAGE_ASPECT;else fh=w/PAGE_ASPECT;return{xmin:cx-fw/2,ymin:cy-fh/2,xmax:cx+fw/2,ymax:cy+fh/2};}
function project(lon:number,lat:number,e:GeoExtent):readonly[number,number]{return[MARGIN+((lon-e.xmin)/Math.max(e.xmax-e.xmin,1e-12))*DRAW_W,MAP_TOP+(1-(lat-e.ymin)/Math.max(e.ymax-e.ymin,1e-12))*DRAW_H];}
function drawRing(doc:jsPDF,ring:Ring,e:GeoExtent){if(ring.length<3)return;const p=ring.map(([x,y])=>project(Number(x),Number(y),e));const rel:Array<[number,number]>=[];for(let i=1;i<p.length;i++)rel.push([p[i][0]-p[i-1][0],p[i][1]-p[i-1][1]]);doc.lines(rel,p[0][0],p[0][1],[1,1],"S",true);}
function drawPolygon(doc:jsPDF,geometry:Polygon,e:GeoExtent,neighbor=false){doc.setDrawColor(neighbor?110:37,neighbor?120:99,neighbor?130:235);doc.setLineWidth(neighbor?.14:.22);if(neighbor)doc.setLineDashPattern([1.2,1],0);for(const r of geometry.rings??[])drawRing(doc,r,e);if(neighbor)doc.setLineDashPattern([],0);}
function ringsExtent(rings:Ring[]):GeoExtent|null{let xmin=Infinity,ymin=Infinity,xmax=-Infinity,ymax=-Infinity;for(const r of rings)for(const p of r){const x=Number(p[0]),y=Number(p[1]);if(Number.isFinite(x)&&Number.isFinite(y)){xmin=Math.min(xmin,x);ymin=Math.min(ymin,y);xmax=Math.max(xmax,x);ymax=Math.max(ymax,y);}}return Number.isFinite(xmin)?{xmin,ymin,xmax,ymax}:null;}
async function rajukQuery<T>(layer:number,params:Record<string,string|number|boolean|undefined>):Promise<T>{const q=new URLSearchParams();for(const[k,v]of Object.entries(params))if(v!==undefined)q.set(k,String(v));q.set("f","json");let r=await fetch(`${RAJUK_DB}/${layer}/query?${q}`,{signal:AbortSignal.timeout(SAT_TIMEOUT)});if(r.status===401||r.status===403){const token=await getValidToken("https://masterplan.rajuk.gov.bd/server/rest/services");q.set("token",token);r=await fetch(`${RAJUK_DB}/${layer}/query?${q}`,{signal:AbortSignal.timeout(SAT_TIMEOUT)});}if(!r.ok)throw new Error(`RAJUK mouza query failed (${r.status})`);return await r.json() as T;}
async function getMouzaContext(mouza:string,jl?:string){const where=`UPPER(mauza) = UPPER('${mouza.replace(/'/g,"''")}')${jl?` AND jl_no='${jl.replace(/'/g,"''")}'`:""}`;const current=await rajukQuery<{features?:MouzaRow[]}>(1,{where,outFields:"mauza,jl_no,m_guid,t_guid,upazila_ps,m_district",returnGeometry:true,resultRecordCount:1});const geometry=current.features?.[0]?.geometry??null;if(!geometry)return{geometry:null,neighbors:[] as MouzaRow[]};const e=ringsExtent(geometry.rings??[]);if(!e)return{geometry,neighbors:[] as MouzaRow[]};const envelope=JSON.stringify({xmin:e.xmin,ymin:e.ymin,xmax:e.xmax,ymax:e.ymax,spatialReference:{wkid:4326}});const data=await rajukQuery<{features?:MouzaRow[]}>(1,{geometry:envelope,geometryType:"esriGeometryEnvelope",inSR:4326,spatialRel:"esriSpatialRelIntersects",outFields:"mauza,jl_no,m_guid,t_guid,upazila_ps,m_district",returnGeometry:true,resultRecordCount:MAX_NEIGHBORS+1});const key=`${mouza.toLowerCase()}|${jl??""}`;return{geometry,neighbors:(data.features??[]).filter(x=>`${text(x.attributes,["mauza","mauza_name"]).toLowerCase()}|${text(x.attributes,["jl_no","jl"])}`!==key).slice(0,MAX_NEIGHBORS)};}
async function satellite(e:GeoExtent):Promise<Buffer>{const p=new URLSearchParams({bbox:`${e.xmin},${e.ymin},${e.xmax},${e.ymax}`,bboxSR:"4326",imageSR:"4326",size:`${SAT_W},${SAT_H}`,format:"jpg",f:"image",dpi:"300",compressionQuality:"78",transparent:"false"});const r=await fetch(`https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/export?${p}`,{signal:AbortSignal.timeout(SAT_TIMEOUT),headers:{accept:"image/jpeg"}});if(!r.ok||!(r.headers.get("content-type")??"").toLowerCase().includes("image/"))throw new Error(`Satellite imagery request failed (${r.status})`);return Buffer.from(await r.arrayBuffer());}
function drawGrid(doc:jsPDF,e:GeoExtent){const xs=e.xmax-e.xmin,ys=e.ymax-e.ymin,sx=xs>.05?.01:xs>.01?.002:.001,sy=ys>.05?.01:ys>.01?.002:.001;doc.setDrawColor(100,105,110);doc.setLineWidth(.06);doc.setFontSize(4);doc.setTextColor(75,80,85);for(let x=Math.ceil(e.xmin/sx)*sx;x<e.xmax;x+=sx){const[px]=project(x,e.ymin,e);doc.line(px,MAP_TOP,px,MAP_TOP+DRAW_H);doc.text(`${x.toFixed(4)}°E`,px+1,MAP_TOP+4);}for(let y=Math.ceil(e.ymin/sy)*sy;y<e.ymax;y+=sy){const[,py]=project(e.xmin,y,e);doc.line(MARGIN,py,MARGIN+DRAW_W,py);doc.text(`${y.toFixed(4)}°N`,MARGIN+1,py-1);}}
function drawLegend(doc:jsPDF,satelliteOn:boolean,layers:string){const y=PAGE_H-9;doc.setFont("helvetica","bold");doc.setFontSize(6);doc.setTextColor(25,30,35);doc.text("Legend",MARGIN,y);doc.setFont("helvetica","normal");doc.setDrawColor(37,99,235);doc.line(MARGIN+15,y-1,MARGIN+24,y-1);doc.text("RS plot",MARGIN+26,y+1);doc.setDrawColor(105,55,180);doc.line(MARGIN+49,y-1,MARGIN+58,y-1);doc.text("MS plot",MARGIN+60,y+1);doc.setDrawColor(110,120,130);doc.setLineDashPattern([1.2,1],0);doc.line(MARGIN+85,y-1,MARGIN+94,y-1);doc.setLineDashPattern([],0);doc.text("Neighboring Mouza",MARGIN+96,y+1);if(satelliteOn)doc.text("Satellite backdrop",MARGIN+148,y+1);doc.text(`Layers: ${layers}`,MARGIN+205,y+1);}

export async function exportMouzaPublicationPdf(input:MouzaPublicationRequest):Promise<MouzaPublicationResult>{const mouza=input.mouza.trim();if(!mouza)throw new Error("Mouza is required");const all:RajukPlotFeature[]=[];for(let offset=0;;offset+=2000){const p=await getPlots({mouza,jl:input.jl,kind:"all",resultRecordCount:2000,resultOffset:offset});const rows=p.features??[];all.push(...rows);if(rows.length<2000)break;}const features=all.filter(f=>input.layers==="combined"?true:input.layers==="ms"?isMs(f):!isMs(f));if(!features.length)throw new Error(`No plots found for ${mouza}`);const raw=extentOf(features);if(!raw)throw new Error("No valid plot geometry found");const fitted=expandExtent(raw);const ctx=await getMouzaContext(mouza,input.jl).catch(()=>({geometry:null,neighbors:[] as MouzaRow[]}));const doc=new jsPDF({orientation:"landscape",unit:"mm",format:[PAGE_W,PAGE_H],compress:true,putOnlyUsedFonts:true});doc.setProperties({title:`LandBD — ${mouza} Mouza Map`,subject:"Complete RS/MS cadastral publication map",creator:"LandBD"});doc.setFillColor(248,249,250);doc.rect(MARGIN,MAP_TOP,DRAW_W,DRAW_H,"F");let sat=false;if(input.satellite){try{doc.addImage(await satellite(fitted),"JPEG",MARGIN,MAP_TOP,DRAW_W,DRAW_H,undefined,"FAST");sat=true;}catch(e){console.warn("Satellite backdrop unavailable; continuing with vector map",e);}}drawGrid(doc,fitted);for(const n of ctx.neighbors)if(n.geometry)drawPolygon(doc,n.geometry,fitted,true);for(const f of features)drawPolygon(doc,f.geometry,fitted,isMs(f));drawAdaptivePlotLabels(doc,features,fitted,project,isMs);doc.setDrawColor(15,45,70);doc.setLineWidth(.8);if(ctx.geometry)for(const r of ctx.geometry.rings??[])drawRing(doc,r,fitted);doc.setFont("helvetica","bold");doc.setFontSize(13);doc.setTextColor(20,30,40);doc.text(`LandBD — ${mouza}`,MARGIN,9);doc.setFontSize(7);doc.setFont("helvetica","normal");const sample=features[0]?.attributes as Record<string,unknown>|undefined;const jlValue=input.jl??text(sample??{},["jl_no","rs_jl_no","ms_jl_no"]);const district=text(sample??{},["m_district","district"]);const upazila=text(sample??{},["upazila_ps","thana_upazila","upazila"]);doc.text(`JL: ${jlValue||"—"}    District: ${district||"—"}    Upazila: ${upazila||"—"}    Plots: ${features.length}`,MARGIN,14);doc.text(`RS/MS: ${input.layers.toUpperCase()}    CRS: EPSG:4326    Output: ${sat?"Satellite + Vector":"Vector"}`,MARGIN,19);drawScaleText(doc,fitted,8);drawNorthArrow(doc);drawScaleBar(doc,fitted);drawLegend(doc,sat,input.layers.toUpperCase());const body=Buffer.from(doc.output("arraybuffer"));return{filename:`landbd-${safePart(mouza)}-${input.layers}${sat?"-satellite":""}-publication.pdf`,contentType:"application/pdf",body,meta:{mouza,width:PAGE_W,height:PAGE_H,zoom:0,resolution:sat?300:0,crs:"EPSG:4326 vector geometry",extent:fitted,tileCount:sat?1:0,plotCount:features.length,satellite:sat}};}
