import { LayerDefinition, LayerRegistry } from "./registry";

export const overlays: LayerDefinition[] = [
  {
    id: "rs-plot-vector",
    displayName: "RS প্লট (ভেক্টর)",
    type: "vector-overlay",
    defaultVisible: true,
    zIndex: 999,
  },
  {
    id: "rajuk-boundary",
    displayName: "রাজউক সীমানা (Boundary)",
    type: "raster-overlay",
    sourceUrl: "Hosted/Overlay_Boundary_Tiles",
    defaultVisible: true,
    maxZoom: 22,
    zIndex: 100,
  },
  {
    id: "rajuk-dap-zone",
    displayName: "ড্যাপ জোন ও সাবজোন",
    type: "raster-overlay",
    sourceUrl: "Hosted/Rajuk_Zone_Subzone_Tiles",
    defaultVisible: false,
    opacity: 0.7,
    maxZoom: 22,
    zIndex: 90,
  },
  {
    id: "dap-landuse",
    displayName: "প্রস্তাবিত ভূমি ব্যবহার (Landuse)",
    type: "raster-overlay",
    sourceUrl: "Hosted/DAP_proposed_landuse",
    defaultVisible: false,
    opacity: 0.6,
    maxZoom: 22,
    zIndex: 85,
  },
  {
    id: "ms-mouza-red",
    displayName: "MS মৌজা ম্যাপ (লাল)",
    type: "raster-overlay",
    sourceUrl: "Hosted/MS_Mauza_Tiles_Final",
    defaultVisible: true,
    opacity: 0.9,
    maxZoom: 22,
    zIndex: 200,
  },
  {
    id: "rs-mouza-tile",
    displayName: "RS মৌজা ম্যাপ (টাইল)",
    type: "raster-overlay",
    sourceUrl: "Hosted/RS_Mauza_Tiles_Final",
    defaultVisible: true,
    maxZoom: 22,
    zIndex: 190,
  },
  {
    id: "rs-mouza-282",
    displayName: "RS মৌজা হাই-রেজ (282 Scale)",
    type: "raster-overlay",
    sourceUrl: "Hosted/RS_Mauza_282Scale",
    defaultVisible: false,
    maxZoom: 22,
    zIndex: 180,
  },
  {
    id: "transport-network",
    displayName: "প্রস্তাবিত পরিবহন নেটওয়ার্ক",
    type: "raster-overlay",
    sourceUrl: "Hosted/Transport_Network_Tiles",
    defaultVisible: false,
    maxZoom: 22,
    zIndex: 300,
  },
  {
    id: "flood-overlay",
    displayName: "বন্যা প্লাবন এলাকা",
    type: "raster-overlay",
    sourceUrl: "Hosted/flood_overlay_lvl11_20",
    defaultVisible: false,
    opacity: 0.6,
    maxZoom: 22,
    zIndex: 80,
  },
  {
    id: "landmarks",
    displayName: "গুরুত্বপূর্ণ স্থাপনা (Landmarks)",
    type: "raster-overlay",
    sourceUrl: "Hosted/Major_Landmarks_V2_TILES",
    defaultVisible: false,
    maxZoom: 22,
    zIndex: 310,
  },
  {
    id: "poi-proposed",
    displayName: "প্রস্তাবিত POI",
    type: "raster-overlay",
    sourceUrl: "Hosted/POI_Proposed_Tiles",
    defaultVisible: false,
    maxZoom: 22,
    zIndex: 320,
  }
];

LayerRegistry.registerMultiple(overlays);
