from pathlib import Path

ROOT = Path('.')
MAP = ROOT / 'src/features/geospatial-map/maplibre/MapLibreMap.tsx'
LAYERS = ROOT / 'src/features/geospatial-map/maplibre/layers.ts'
TYPES = ROOT / 'src/features/geospatial-map/maplibre/types.ts'

text = MAP.read_text()

def replace_once(old, new, label):
    global text
    if old not in text:
        raise SystemExit(f'Expected {label} anchor was not found; refusing unsafe rewrite.')
    text = text.replace(old, new, 1)

replace_once('  Database,\n  Layers3,', '  Database,\n  Download,\n  Filter,\n  Layers3,', 'icon imports')
replace_once('import { BASEMAP_RASTER_LAYERS, RAJUK_RASTER_LAYERS, VECTOR_LAYER_STYLES } from "./layers";', 'import { BASEMAP_RASTER_LAYERS, RAJUK_RASTER_LAYERS, VECTOR_LAYER_STYLES } from "./layers";\nimport { exportMapAsHighResolutionPng } from "./exportMap";', 'map imports')
replace_once('  const identifyModeRef = useRef(true);', '  const identifyModeRef = useRef(true);\n  const mouzaRef = useRef("");\n  const loadExtentRef = useRef<(() => Promise<void>) | null>(null);', 'map refs')
replace_once('  const [routingCalculator, setRoutingCalculator] = useState<"khatiyan" | "faraez" | null>(null);', '  const [routingCalculator, setRoutingCalculator] = useState<"khatiyan" | "faraez" | null>(null);\n  const [mouza, setMouza] = useState("");\n  const [mouzaOpen, setMouzaOpen] = useState(false);\n  const [mouzaLoaded, setMouzaLoaded] = useState(false);\n  const [exporting, setExporting] = useState(false);', 'map state')
replace_once('  identifyModeRef.current = identifyMode;', '  identifyModeRef.current = identifyMode;\n  mouzaRef.current = mouza;', 'map state refs')
replace_once('      renderWorldCopies: false,\n    });', '      renderWorldCopies: false,\n      preserveDrawingBuffer: true,\n    });', 'preserveDrawingBuffer')

old_click = '''    const handleClick = (event: maplibregl.MapMouseEvent) => {\n      if (!identifyModeRef.current) return;\n  \n const features = map.queryRenderedFeatures(event.point, {\n   layers: ["vector-rs-boundary-fill", "vector-ms-boundary-fill"],\n });\n      const vector = features.find((feature: MapGeoJSONFeature) => feature.geometry?.type === "Polygon");\n      if (!vector) return;\n      const sourceKind = String(vector.properties?._layer_source ?? "").toLowerCase() === "ms" || String(vector.properties?.plot_kind ?? "").toLowerCase() === "ms" ? "ms" : "rs";\n      const parcel = renderedFeatureToRajuk(vector, sourceKind);\n      if (!parcel) return;\n      setSelected(parcel);\n      setResults((current) => {\n        const id = parcel.attributes.objectid;\n        const filtered = current.filter((item) => item.attributes.objectid !== id);\n        return [parcel, ...filtered];\n      });\n      setTab("results");\n      setPanelOpen(true);\n      updateSourceData(map, VECTOR_SOURCES.selectedPlot, featuresToFc([parcel]) as FeatureCollection<Geometry>);\n    };'''
new_click = '''    const handleClick = async (event: maplibregl.MapMouseEvent) => {\n      if (!identifyModeRef.current) return;\n      const params = new URLSearchParams({\n        action: "identify",\n        lat: String(event.lngLat.lat),\n        lng: String(event.lngLat.lng),\n      });\n      try {\n        const response = await fetchWithTimeout(`/api/rajuk/query?${params.toString()}`);\n        const data = (await response.json().catch(() => null)) as { features?: RajukPlotFeature[]; error?: string } | null;\n        if (!response.ok) throw new Error(data?.error || "দাগ শনাক্ত করা যায়নি");\n        const found = Array.isArray(data?.features) ? data.features : [];\n        setResults(found);\n        setSelected(found[0] ?? null);\n        setTab("results");\n        setPanelOpen(true);\n        if (found[0]) updateSourceData(map, VECTOR_SOURCES.selectedPlot, featuresToFc([found[0]]) as FeatureCollection<Geometry>);\n        else {\n          updateSourceData(map, VECTOR_SOURCES.selectedPlot, EMPTY_GEOJSON);\n          notify("এই অবস্থানে কোনো দাগ পাওয়া যায়নি");\n        }\n      } catch (error) {\n        if (error instanceof DOMException && error.name === "AbortError") return;\n        notify(error instanceof Error ? error.message : "দাগ শনাক্ত করা যায়নি");\n      }\n    };'''
replace_once(old_click, new_click, 'coordinate identify click handler')

replace_once('        VECTOR_LAYER_STYLES.msBoundaryLine,\n        VECTOR_LAYER_STYLES.selectedPlotFill,', '        VECTOR_LAYER_STYLES.msBoundaryLine,\n        VECTOR_LAYER_STYLES.rsPlotLabels,\n        VECTOR_LAYER_STYLES.msPlotLabels,\n        VECTOR_LAYER_STYLES.selectedPlotFill,', 'label layers')
replace_once('      map.off("zoomend", handleMove);\n      map.remove();', '      map.off("zoomend", handleMove);\n      loadExtentRef.current = null;\n      map.remove();', 'extent cleanup')

old_query = '''      const query = (kind: "rs" | "ms") => {\n        const params = new URLSearchParams({\n          action: "extent",\n          kind,\n          xmin: String(bounds.getWest()),\n          ymin: String(bounds.getSouth()),\n          xmax: String(bounds.getEast()),\n          ymax: String(bounds.getNorth()),\n          limit: "400",\n        });\n        return fetchWithTimeout(`/api/rajuk/query?${params.toString()}`, {}, controller.signal).then(async (response) => {\n          if (!response.ok) throw new Error((await response.json().catch(() => null))?.error || `RAJUK ${kind.toUpperCase()} request failed`);\n          return (await response.json()) as { features?: RajukPlotFeature[] };\n        });\n      };'''
new_query = '''      const selectedMouza = mouzaRef.current.trim();\n      const query = selectedMouza\n        ? () => {\n            const params = new URLSearchParams({ action: "plots", mouza: selectedMouza, kind: "all", limit: "800" });\n            return fetchWithTimeout(`/api/rajuk/query?${params.toString()}`, {}, controller.signal).then(async (response) => {\n              if (!response.ok) throw new Error((await response.json().catch(() => null))?.error || "নির্বাচিত মৌজার দাগ লোড করা যায়নি");\n              return (await response.json()) as { features?: RajukPlotFeature[] };\n            });\n          }\n        : (kind: "rs" | "ms") => {\n            const params = new URLSearchParams({ action: "extent", kind, xmin: String(bounds.getWest()), ymin: String(bounds.getSouth()), xmax: String(bounds.getEast()), ymax: String(bounds.getNorth()), limit: "400" });\n            return fetchWithTimeout(`/api/rajuk/query?${params.toString()}`, {}, controller.signal).then(async (response) => {\n              if (!response.ok) throw new Error((await response.json().catch(() => null))?.error || `RAJUK ${kind.toUpperCase()} request failed`);\n              return (await response.json()) as { features?: RajukPlotFeature[] };\n            });\n          };'''
replace_once(old_query, new_query, 'extent query')

old_response = '''        const [rs, ms] = await Promise.all([query("rs"), query("ms")]);\n        if (controller.signal.aborted || requestId !== extentRequestIdRef.current) return;\n        const rsFeatures = Array.isArray(rs.features) ? rs.features : [];\n        const msFeatures = Array.isArray(ms.features) ? ms.features : [];\n        updateSourceData(map, VECTOR_SOURCES.rsBoundary, featuresToFc(rsFeatures) as FeatureCollection<Geometry>);\n        updateSourceData(map, VECTOR_SOURCES.msBoundary, featuresToFc(msFeatures) as FeatureCollection<Geometry>);\n        setVectorStatus(`${rsFeatures.length + msFeatures.length}টি দাগ লোড হয়েছে`);'''
new_response = '''        if (selectedMouza) {\n          const data = await query();\n          if (controller.signal.aborted || requestId !== extentRequestIdRef.current) return;\n          const found = Array.isArray(data.features) ? data.features : [];\n          const rsFeatures = found.filter((feature) => isRsFeature(feature));\n          const msFeatures = found.filter((feature) => isMsFeature(feature));\n          updateSourceData(map, VECTOR_SOURCES.rsBoundary, featuresToFc(rsFeatures) as FeatureCollection<Geometry>);\n          updateSourceData(map, VECTOR_SOURCES.msBoundary, featuresToFc(msFeatures) as FeatureCollection<Geometry>);\n          setMouzaLoaded(true);\n          setVectorStatus(`${found.length}টি দাগ লোড হয়েছে`);\n        } else {\n          const [rs, ms] = await Promise.all([query("rs"), query("ms")]);\n          if (controller.signal.aborted || requestId !== extentRequestIdRef.current) return;\n          const rsFeatures = Array.isArray(rs.features) ? rs.features : [];\n          const msFeatures = Array.isArray(ms.features) ? ms.features : [];\n          updateSourceData(map, VECTOR_SOURCES.rsBoundary, featuresToFc(rsFeatures) as FeatureCollection<Geometry>);\n          updateSourceData(map, VECTOR_SOURCES.msBoundary, featuresToFc(msFeatures) as FeatureCollection<Geometry>);\n          setMouzaLoaded(false);\n          setVectorStatus(`${rsFeatures.length + msFeatures.length}টি দাগ লোড হয়েছে`);\n        }'''
replace_once(old_response, new_response, 'extent response')

replace_once('''    }\n  }, []);\n\n  useEffect(() => {''', '''    }\n    loadExtentRef.current = loadExtent;\n  }, []);\n\n  const applyMouzaFilter = useCallback(() => {\n    if (!mouza.trim()) return notify("মৌজার নাম লিখুন");\n    setMouzaLoaded(false);\n    setMouzaOpen(false);\n    void loadExtentRef.current?.();\n  }, [mouza, notify]);\n\n  const exportHighResolutionMap = useCallback(async () => {\n    const map = mapRef.current;\n    if (!map || !mouzaLoaded) return;\n    setExporting(true);\n    try {\n      await exportMapAsHighResolutionPng(map, { width: 3840, height: 2160, filename: `landbd-${mouza.trim().replace(/[^a-zA-Z0-9\\u0980-\\u09FF]+/g, "-") || "mouza"}-4k.png` });\n      notify("উচ্চ-রেজোলিউশনের মানচিত্র ডাউনলোড হয়েছে");\n    } catch (error) {\n      notify(error instanceof Error ? error.message : "মানচিত্র ডাউনলোড করা যায়নি");\n    } finally {\n      setExporting(false);\n    }\n  }, [mouza, mouzaLoaded, notify]);\n\n  useEffect(() => {''', 'post-map callbacks')

replace_once('    if (map.getLayer(VECTOR_LAYERS.msBoundaryLine)) map.setLayoutProperty(VECTOR_LAYERS.msBoundaryLine, "visibility", showMsBoundary ? "visible" : "none");', '    if (map.getLayer(VECTOR_LAYERS.msBoundaryLine)) map.setLayoutProperty(VECTOR_LAYERS.msBoundaryLine, "visibility", showMsBoundary ? "visible" : "none");\n    if (map.getLayer(VECTOR_LAYERS.rsPlotLabels)) map.setLayoutProperty(VECTOR_LAYERS.rsPlotLabels, "visibility", showRsBoundary ? "visible" : "none");\n    if (map.getLayer(VECTOR_LAYERS.msPlotLabels)) map.setLayoutProperty(VECTOR_LAYERS.msPlotLabels, "visibility", showMsBoundary ? "visible" : "none");', 'label visibility')

replace_once('''        <button onClick={goToMyLocation} disabled={locating} className="rounded-xl border border-border bg-background/95 p-2.5 shadow-lg backdrop-blur hover:bg-muted" aria-label="আমার অবস্থান">{locating ? <Loader2 className="animate-spin" size={19} /> : <LocateFixed size={19} />}</button>\n      </div>''', '''        <button onClick={goToMyLocation} disabled={locating} className="rounded-xl border border-border bg-background/95 p-2.5 shadow-lg backdrop-blur hover:bg-muted" aria-label="আমার অবস্থান">{locating ? <Loader2 className="animate-spin" size={19} /> : <LocateFixed size={19} />}</button>\n        <button onClick={() => setMouzaOpen((value) => !value)} className={`rounded-xl border border-border p-2.5 shadow-lg backdrop-blur ${mouzaOpen ? "bg-primary text-primary-foreground" : "bg-background/95 hover:bg-muted"}`} aria-label="মৌজা ফিল্টার"><Filter size={19} /></button>\n        {mouzaOpen && <form onSubmit={(event) => { event.preventDefault(); applyMouzaFilter(); }} className="absolute left-0 top-12 w-72 rounded-xl border border-border bg-background/95 p-3 shadow-xl backdrop-blur">\n          <label className="mb-1 block text-xs font-bold">মৌজার নাম</label>\n          <div className="flex gap-2"><input value={mouza} onChange={(event) => setMouza(event.target.value)} placeholder="মৌজার নাম লিখুন" className="min-w-0 flex-1 rounded-lg border border-border bg-background px-3 py-2 text-sm outline-none focus:ring-2 focus:ring-primary/30" /><button type="submit" className="rounded-lg bg-primary px-3 py-2 text-xs font-bold text-primary-foreground">লোড</button></div>\n          <p className="mt-2 text-[10px] text-muted-foreground">শুধু নির্বাচিত মৌজার দাগ লোড হবে।</p>\n        </form>}\n      </div>''', 'Mouza control')

replace_once('''        <button onClick={() => setPanelOpen((value) => !value)} className="rounded-xl border border-border bg-background/95 p-2.5 shadow-lg backdrop-blur hover:bg-muted" aria-label="প্যানেল">{panelOpen ? <X size={19} /> : <PanelRight size={19} />}</button>\n      </div>''', '''        {mouzaLoaded && <button onClick={() => void exportHighResolutionMap()} disabled={exporting} className="rounded-xl border border-border bg-background/95 p-2.5 shadow-lg backdrop-blur hover:bg-muted disabled:opacity-50" aria-label="মানচিত্র ডাউনলোড">{exporting ? <Loader2 className="animate-spin" size={19} /> : <Download size={19} />}</button>}\n        <button onClick={() => setPanelOpen((value) => !value)} className="rounded-xl border border-border bg-background/95 p-2.5 shadow-lg backdrop-blur hover:bg-muted" aria-label="প্যানেল">{panelOpen ? <X size={19} /> : <PanelRight size={19} />}</button>\n      </div>''', 'export control')

MAP.write_text(text)

layer = LAYERS.read_text()
if 'SymbolLayerSpecification' not in layer:
    layer = layer.replace('  RasterLayerSpecification,\n', '  RasterLayerSpecification,\n  SymbolLayerSpecification,\n', 1)
layer = layer.replace('"fill-color": "#3b82f6",\n      "fill-opacity": 0.08,', '"fill-color": "#bfdbfe",\n      "fill-opacity": 0.045,', 1)
layer = layer.replace('"fill-color": "#a78bfa",\n      "fill-opacity": 0.08,', '"fill-color": "#ddd6fe",\n      "fill-opacity": 0.045,', 1)
if 'rsPlotLabels:' not in layer:
    block = '''  rsPlotLabels: {\n    id: VECTOR_LAYERS.rsPlotLabels,\n    type: "symbol",\n    source: VECTOR_SOURCES.rsBoundary,\n    layout: { "text-field": ["coalesce", ["get", "rs_plot_no"], ["get", "plot_no"], ""], "text-size": 11, "text-anchor": "center", "text-allow-overlap": false, "symbol-placement": "point" },\n    paint: { "text-color": "#1e3a8a", "text-halo-color": "#ffffff", "text-halo-width": 1.25, "text-halo-blur": 0.15 },\n  } satisfies SymbolLayerSpecification,\n\n  msPlotLabels: {\n    id: VECTOR_LAYERS.msPlotLabels,\n    type: "symbol",\n    source: VECTOR_SOURCES.msBoundary,\n    layout: { "text-field": ["coalesce", ["get", "ms_plot_no"], ["get", "plot_no"], ""], "text-size": 11, "text-anchor": "center", "text-allow-overlap": false, "symbol-placement": "point" },\n    paint: { "text-color": "#5b21b6", "text-halo-color": "#ffffff", "text-halo-width": 1.25, "text-halo-blur": 0.15 },\n  } satisfies SymbolLayerSpecification,\n\n'''
    layer = layer.replace('  locationPoint: {', block + '  locationPoint: {', 1)
LAYERS.write_text(layer)

types = TYPES.read_text()
if 'rsPlotLabels:' not in types:
    types = types.replace('  locationPoint: "vector-location-point",\n', '  locationPoint: "vector-location-point",\n  rsPlotLabels: "vector-rs-plot-labels",\n  msPlotLabels: "vector-ms-plot-labels",\n', 1)
TYPES.write_text(types)
